openapi: 3.0.0
info:
  title: Photo Sharing API
  version: 1.0.0
  description: API for a photo-sharing app
servers:
  - url: http://localhost:8000/api
tags:
  - name: Images
    description: Endpoints related to image operations
  - name: Authentication
    description: Endpoints related to user authentication
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The user ID
          example: 60c72b2f9b1e8a5f4c8d4e45
        username:
          type: string
          description: The username of the user
          example: john_doe
        email:
          type: string
          description: The email of the user
          example: john@example.com
        password:
          type: string
          description: The password of the user
          example: password123
        isVerified:
          type: boolean
          description: Whether the user's email is verified
          example: false
        OTPVerificationToken:
          type: object
          properties:
            OTP:
              type: string
              description: The OTP for verification
              example: 123456
            expires:
              type: string
              format: date-time
              description: The expiration time of the OTP
              example: 2023-01-01T00:00:00Z
        verificationToken:
          type: object
          properties:
            token:
              type: string
              description: The verification token
              example: abcdef123456
            expires:
              type: string
              format: date-time
              description: The expiration time of the token
              example: 2023-01-01T00:00:00Z
        createdAt:
          type: string
          format: date-time
          description: The creation time of the user
          example: 2023-01-01T00:00:00Z
        updatedAt:
          type: string
          format: date-time
          description: The last update time of the user
          example: 2023-01-01T00:00:00Z
    Image:
      type: object
      properties:
        id:
          type: string
          description: The image ID
          example: 60c72b2f9b1e8a5f4c8d4e46
        title:
          type: string
          description: The title of the image
          example: Beautiful Sunset
        imageUrl:
          type: string
          description: The URL of the image
          example: http://example.com/images/sunset.jpg
        public_id:
          type: string
          description: The public ID of the image in the image storage service
          example: abc123
        user:
          type: string
          description: The user ID who uploaded the image
          example: 60c72b2f9b1e8a5f4c8d4e45
        createdAt:
          type: string
          format: date-time
          description: The creation time of the image
          example: 2023-01-01T00:00:00Z
        updatedAt:
          type: string
          format: date-time
          description: The last update time of the image
          example: 2023-01-01T00:00:00Z
paths:
  /images:
    get:
      tags:
        - Images
      summary: Retrieve a list of images
      responses:
        "200":
          description: A list of images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"

    post:
      tags:
        - Images
      summary: Upload a new image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the image
                  example: Beautiful Sunset
                image:
                  type: string
                  format: byte
                  description: The base64-encoded image
                  example: iVBORw0KGgoAAAANSUhEUgAAAAUA...
      responses:
        "201":
          description: The uploaded image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"

  /images/{id}:
    put:
      tags:
        - Images
      summary: Update an image
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The updated title of the image
                  example: Updated Title
      responses:
        "200":
          description: The updated image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          description: The image was not found

    delete:
      tags:
        - Images
      summary: Delete an image
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: The image was deleted
        "404":
          description: The image was not found
